// constants/screens.ts

const SCREENS = {
  // Support Stack Screens
  SUPPORT_HOME_SCREEN: 'SUPPORT_HOME_SCREEN',
  BIOMETRIC_DEVICE_SCREEN: 'BIOMETRIC_DEVICE_SCREEN',
  TICKETING_SCREEN: 'TICKETING_SCREEN',
  CONTACT_US_SCREEN: 'CONTACT_US_SCREEN',
  TOP_UP_REQUEST_SCREEN: 'TOP_UP_REQUEST_SCREEN',
  TOP_UP_HISTORY_SCREEN: 'TOP_UP_HISTORY_SCREEN',
  ADD_MONEY_SCREEN: 'ADD_MONEY_SCREEN',
  PAYMENT_REQUEST_SCREEN: 'PAYMENT_REQUEST_SCREEN',
  PAYMENT_HISTORY_SCREEN: 'PAYMENT_HISTORY_SCREEN',
  PAYMENT_BANKS_SCREEN: 'PAYMENT_BANKS_SCREEN',

  // Settings Stack
  SETTINGS_HOME_SCREEN: 'SETTINGS_HOME_SCREEN',
  CREATE_SUB_USER_SCREEN: 'CREATE_SUB_USER_SCREEN',
  CHANGE_TPIN_SCREEN: 'CHANGE_TPIN_SCREEN',
  MY_CERTIFICATE_SCREEN: 'MY_CERTIFICATE_SCREEN',
  LOW_BALANCE_ALERT_SCREEN: 'LOW_BALANCE_ALERT_SCREEN',
  ID_CARD_SCREEN: 'ID_CARD_SCREEN',

  // Funding Stack
  FUNDING_HOME_SCREEN: 'FUNDING_HOME_SCREEN',
  FUND_REQUEST_SCREEN: 'FUND_REQUEST_SCREEN',
  WALLET_TO_WALLET_SCREEN: 'WALLET_TO_WALLET_SCREEN',
  FUND_TRANSFER_SCREEN: 'FUND_TRANSFER_SCREEN',
  FUND_REVERSAL_SCREEN: 'FUND_REVERSAL_SCREEN',
  WALLET_TO_BANK_SCREEN: 'WALLET_TO_BANK_SCREEN',

  // Reports Stack
  REPORTS_HOME_SCREEN: 'REPORTS_HOME_SCREEN',
  COMMISSION_CHARGES_SCREEN: 'COMMISSION_CHARGES_SCREEN',
  WALLET_REPORT_SCREEN: 'WALLET_REPORT_SCREEN',
  NETWORK_TRANSACTION_SCREEN: 'NETWORK_TRANSACTION_SCREEN',
  SEARCH_TRANSACTION_SCREEN: 'SEARCH_TRANSACTION_SCREEN',
  FUND_LOADING_SCREEN: 'FUND_LOADING_SCREEN',
  PENDING_TRANSACTION_SCREEN: 'PENDING_TRANSACTION_SCREEN',
  DEBIT_HISTORY_SCREEN: 'DEBIT_HISTORY_SCREEN',
  DOWNLINE_BALANCE_SCREEN: 'DOWNLINE_BALANCE_SCREEN',

  // Common / Shared Stack
  NOTIFICATIONS_SCREEN: 'NOTIFICATIONS_SCREEN',

  // profile
  PROFILE_HOME_SCREEN: 'PROFILE_HOME_SCREEN',

  // products
  PRODUCTS_HOME_SCREEN: 'PRODUCTS_HOME_SCREEN',

  // Payment Gateway
  PG_SCREEN: 'PG_SCREEN',

  // Payout
  PAYOUT_SCREEN: 'PAYOUT_SCREEN',

  // DMT
  DMT_SCREEN: 'DMT_SCREEN',
  ADD_REMITTER_SCREEN: 'ADD_REMITTER_SCREEN',

  // MPOS
  MPOS_SCREEN: 'MPOS_SCREEN',

  // AEPS
  AEPS_SCREEN: 'AEPS_SCREEN',
  AEPS_OPTION_SELECTION: 'AEPS_OPTION_SELECTION',

  // Bill Payment / BBPS
  BILL_PAYMENT_SCREEN: 'BILL_PAYMENT_SCREEN',
  PAY_SCREEN: 'PAY_SCREEN',
} as const;

export type ScreenName = keyof typeof SCREENS;

export default SCREENS;
